bookmarks/bookmarks/models.py
from datetime import datetime

from sqlalchemy import desc

from bookmarks import db
from ..tags.models import tags, Tag


class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.String(300))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    _tags = db.relationship('Tag', secondary=tags, lazy='joined', backref=db.backref('bookmark', lazy='dynamic'))

    @staticmethod
    def latest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)

    @property
    def tags(self):
        return ','.join([tag.name for tag in self._tags])

    @tags.setter
    def tags(self, text):
        if text:
            self._tags = [Tag.get_or_create(name) for name in text.split(',')]

    def __repr__(self):
        return f'<Bookmark {self.url}>'

bookmarks/tags/models.py
from bookmarks import db

tags = db.Table('bookmark_tag',
                db.Column('bookmark_id', db.Integer, db.ForeignKey('bookmark.id')),
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                )  # middle table


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    @staticmethod
    def get_or_create(name):
        try:
            return Tag.query.filter_by(name=name).one()
        except Exception:
            return Tag(name=name)

    @staticmethod
    def all():
        return Tag.query.all()

    def __repr__(self):
        return f'<Tag {self.name}>'

bookmarks/bookmarks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired, url, Regexp


class BookmarkForm(FlaskForm):
    url = URLField('URL for bookmark:', validators=[DataRequired(), url()])
    description = StringField('Optional description')
    tags = StringField('Tags', validators=[Regexp(r'[a-zA-Z0-9, ]*$', message='Tags can only contain letters and numbers')])
    # $ can not end for any other letter/number
    submit = SubmitField('Submit')

bookmarks/__init__.py
import os

from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
login_manager = LoginManager()

basedir = os.path.abspath(os.path.dirname(__file__))


def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(basedir, 'bookmarks.db')}"
    app.config['SECRET_KEY'] = 'dupa'

    from bookmarks.views import bp_main
    from .auth.views import bp_auth
    from .bookmarks.views import bp_bookmark
    from .tags.views import bp_tag

    app.register_blueprint(bp_main)
    app.register_blueprint(bp_auth)
    app.register_blueprint(bp_bookmark)
    app.register_blueprint(bp_tag)

    db.init_app(app)

    Migrate(app, db)

    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    return app

bookmarks/bookmarks/views.py
from flask import Blueprint, render_template, url_for, abort, flash, request
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from bookmarks import db
from .models import Bookmark
from ..bookmarks.forms import BookmarkForm

bp_bookmark = Blueprint('bookmark', __name__, url_prefix='/bookmarks')


@bp_bookmark.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = BookmarkForm()
    if form.validate_on_submit():
        url = form.url.data
        description = form.description.data

        tags = form.tags.data

        bm = Bookmark(url=url, description=description, user=current_user, tags=tags)
        db.session.add(bm)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('bookmark_form.html', form=form, title='Add bookmark')


@bp_bookmark.route('/edit/<int:bookmark_id>', methods=['GET', 'POST'])
@login_required
def edit(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)

    if current_user != bookmark.user:
        abort(403)

    form = BookmarkForm(obj=bookmark)

    if form.validate_on_submit():
        form.populate_obj(bookmark)  # add data from form to bookmark
        db.session.commit()

        flash(f'Saved {bookmark.description}')

        return redirect(url_for('auth.user', username=current_user.username))

    return render_template('bookmark_form.html', form=form, title='Edit bookmark')


@bp_bookmark.route('/delete/<int:bookmark_id>', methods=['GET', 'POST'])
@login_required
def delete(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)

    if current_user != bookmark.user:
        abort(403)

    if request.method == 'POST':
        db.session.delete(bookmark)
        db.session.commit()

        flash(f'Bookmark {bookmark.description} has been removed.')

        return redirect(url_for('auth.user', username=current_user.username))

    else:
        flash('Please confirm deleting the bookmark.')

    return render_template('confirm_delete.html', bookmark=bookmark)

bookmarks/tags/views.py
from flask import Blueprint, render_template

from ..tags.models import Tag

bp_tag = Blueprint('tag', __name__, url_prefix='/tags')


@bp_tag.route('/<name>')
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('tag.html', tag=tag)

bookmarks/views.py
from flask import Blueprint, render_template

from bookmarks.bookmarks.models import Bookmark
from .tags.models import Tag

bp_main = Blueprint('main', __name__, url_prefix='/')


@bp_main.route('/')
def home():
    return render_template('index.html', new_bookmarks=Bookmark.latest(5))


@bp_main.context_processor
def inject_tags():
    return dict(all_tags=Tag.all())

bookmarks/templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
<div class="header-container">
    <header class="wrapper clearfix"><a href="{{ url_for('main.home')}}">
        <h1>Bookmarks</h1>
    </a>
        <nav>
            <ul>
                <li><a href="{{ url_for('bookmark.add')}}">Add bookmark</a></li>

                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    <a class="nav-link" href="{{ url_for('auth.user', username=current_user.username) }}">Profile</a>
                </li>
                {% else %}

                <li><a href="{{ url_for('auth.login')}}">Login</a></li>
                <li><a href="{{ url_for('auth.signup')}}">Signup</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>
</div>
<div class="main-container">
    <div class="main wrapper clearfix">
        {% block content %}
        {% endblock %}
        <aside></aside>
    </div>
</div>


</body>
</html>

bookmarks/templates/bookmark_form.html
{% extends "_base.html" %}

{% block content %}

<h2>{{ title }}</h2>
{% include 'partials/_form.html' %}

{% endblock %}

bookmarks/templates/confirm_delete.html
{% extends "_base.html" %}

{% block content %}
<form action="" method="post">
    <h3>Are you sure you wanted delete this bookmark?</h3>
    <a href="{{ url_for('auth.user', username=current_user.username) }}">No, take me out of here.</a>
    <button>Yes, delete it.</button>
</form>
{% endblock %}

bookmarks/templates/index.html
{% extends "_base.html" %}
{% block content %}
<article>
    <header>
        <h1>bookmarks</h1>
    </header>
    <section>
        <h2>Recently added</h2>
        {% if new_bookmarks.count() > 0 %}
            {% for bm in new_bookmarks %}
                <li><a href="{{ bm.url }}">{{ bm.description }}</a></li>
            {% endfor %}
        {% else %}
            No bookmarks yet.
        {% endif %}
    </section>
</article>
{% endblock %}

bookmarks/templates/macros/form_field_macros.html
{% macro render_field_old(field) %}
  <div class="form-group">
      {% with invalid = 'form-control is-invalid' if field.errors else 'form-control' %}
      {% if field.type != 'SubmitField' and field.name != 'csrf_token' and field.type != 'HiddenField' and field.widget.input_type != 'hidden' %}
            {{ field.label(class="form-label") }}
      {% endif %}

      {{ field (class=invalid) }}

      {% if field.errors %}
      <div class="invalid-feedback">
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
      </div>
      {% endif %}
    {% endwith %}
  </div>
{% endmacro %}

{% macro render_field(field) %}
<div class="form-group">
    {% with cls = "form-control is-invalid" if field.errors else "form-control" %}
        {%  if field.widget.input_type == "submit" %}
            {% set cls = "btn btn-outline-primary custom-btn" %}
        {% endif %}
        {% if field.widget.input_type == 'checkbox' %}
            {{ field }}
            {{ field.label }}
        {% else %}
            {% if field.widget.input_type != 'hidden' and field.widget.input_type != 'submit' %}
                {{ field.label(class="form-label") }}:
            {% endif %}
            {{ field(class=cls) }}
        {% endif %}
    {% endwith %}
    {% for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
</div>
{% endmacro %}

{% macro error_messages(form) %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field in form.errors %}
        <b>{{ form[field].label | capitalize }} field has following errors:</b>
            {% for error in form.errors[field] %}
                {{ error }} <br>
            {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
{% endmacro %}

bookmarks/templates/partials/_bookmark.html
<div class="bookmark">
    <a href="{{ bookmark.url }}" class="header" target="_blank">
    <h3 class="description">{{ bookmark.description|truncate(50, killwords=True) }}</h3>
    <span class="url">{{ bookmark.url|truncate(50, killwords=True) }}</span>
    </a>
    <div class="info">
        <span class="tags">
            {% if bookmark.tags %}

                {% for t in bookmark._tags %}
                    <a href="{{ url_for('tag.tag', name=t.name) }}">{{ t.name }}</a>
                {% endfor %}

            {% endif %}
        </span>
        Added by <a href="{{ url_for('auth.user', username=bookmark.user.username) }}">{{ bookmark.user.username }}</a>
        {% if current_user == bookmark.user and links %}
        <span class="editlinks">
            <a href="{{ url_for('bookmark.edit', bookmark_id=bookmark.id) }}">Edit</a>
            <a href="{{ url_for('bookmark.delete', bookmark_id=bookmark.id) }}">Delete</a>
            {% endif %}
        </span>
    </div>
</div>

bookmarks/templates/partials/_bookmarks_list.html
<ul class="bookmarks">
    {% for bookmark in bookmarks %}
    <li>
        {% include 'partials/_bookmark.html' %}
    </li>
    {% endfor %}
</ul>

bookmarks/templates/partials/_form.html
{% from 'macros/form_field_macros.html' import render_field %}
{% from 'macros/form_field_macros.html' import error_messages %}

<form action="{{ action }}" method="{{ method if method else 'POST' }}" novalidate {% if enctype %} enctype="multipart/form-data" {% endif %}>

    {{ error_messages(form) }}
    {% for f in form %}
        {{ render_field(f) }}
    {% endfor %}
</form>

bookmarks/templates/tag.html
{% extends "_base.html" %}
{% block content %}
<article>
    <header>
        <h1>Bookmarks tagged {{ tag.name }}</h1>
    </header>
    <section>

        {% if tag.bookmark.count() > 0 %}

        {% with bookmarks=tag.bookmark %}
            {% include 'partials/_bookmarks_list.html' %}
        {% endwith %}

        {% else %}
            No bookmarks yet.
        {% endif %}
    </section>
</article>
{% endblock %}

bookmarks/templates/user.html
{% extends "_base.html" %}

{% block content %}
<article>
    <header>
        <h1>Bookmarks for {{ user.username }}</h1>
        {% if bookmarks.count() > 0 %}
            {% include 'partials/_bookmarks_list.html' %}
        {% else %}
            This user has not added any bookmarks yet.
        {% endif %}
    </header>
</article>
{% endblock %}